# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 927d3ab9f81b026a858ee121f117ae3ddc8db69a1dea171fc1fcef6c9a3d311aaac24aae6c5e4557f103b3f743e7e29e1fbf2cfcbe7f339d62c524cb5f8c2581

test:
  secret_key_base: 00b7aa138b4bbb60aa7fd559f1af2ee3ed655d40714fb4bb9f6898d299506273c6553523c9c8323f061343348272c3bd240190c5044ae3e97700affe657910be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
